### ISSUE TITLE
Incorporate real Library examples in text & interactive exercise

### ISSUE THREAD

**Issue by ndalyrose** [data-lessons/library-data-intro-DEPRECATED#27]
Reviewed this lesson today with some colleagues and thinking it could benefit from more concrete/worked out Library examples of regex in action, as well as an interactive exercise option (ie, provide a text file with typical library-style data such as messy catalogue records and guide participants through using various regular expressions to query them).

**Comment by weaverbel** [comment]
Agree @ndalyrose. @pitviper6 said pretty much the same thing when she taught this yesterday at our workshop in Boston. Juliane, any thoughts?

**Comment by drjwbaker** [comment]
@ndalyrose I've assigned this to you as I presume (hope?) the London site will take this on during the spring.

**Comment by weaverbel** [comment]
Or the summer, autumn or winter - tee hee - I know you meant the sprint @drjwbaker. Should this issue be moved over to the repo for the sprint or is it enough to have it marked mozsprint here? I just thought other sprinters mightn't find it here despite the label, and some other sprinters might want to do some regex stuff.

**Comment by weaverbel** [comment]
Definitely think this should be an issue against https://github.com/data-lessons/librarycarpentry or it might get overlooked @ndalyrose @drjwbaker

**Comment by drjwbaker** [comment]
@weaverbel There are mozsprint flagged issues in more than one lesson repo. Perhaps we can sweep them all towards the sprint repo in our pre-sprint actions?

**Comment by weaverbel** [comment]
Maybe it's fine to leave them then @drjwbaker. Pre-sprint, we can do a new issue on the sprint repo that links to all the other issues on all the other repos. That might be simpler.

**Comment by drjwbaker** [comment]
@weaverbel Agreed. 

@ndalyrose So you know, I maintain this lesson with @ccronje. I look forward to working on these examples with you!

**Comment by antonangelo** [comment]
Are capturing groups (and global replacement) out of scope for this lesson? A simple example might be to change US dates to rest-of-the-world dates.

**Comment by weaverbel** [comment]
I like the sound of that @antonangelo ! Are you able to write it up? Are you joining the sprint, by the way?

**Comment by antonangelo** [comment]
I hope so, (just got time off from the boss! :D

**Comment by weaverbel** [comment]
Great @antonangelo - be sure to add your details to the etherpad so we have a full list of who's involved.
pad.software-carpentry.org/lc2017

**Comment by drjwbaker** [comment]
Refine lesson has something similar, this time on reversing author names http://data-lessons.github.io/library-openrefine/04-basic-functions-II/ (see exercise 10)

**Comment by antonangelo** [comment]
@drjwbaker So it does!  And that's a good example in a place where you can use it.

**Comment by drjwbaker** [comment]
I think having a comparable task in the shell lesson is powerful: shows the same thing can be done in different places in different ways.

**Comment by drjwbaker** [comment]
I think having a comparable task in the shell lesson is powerful: shows the same thing can be done in different places in different ways.

**Comment by drjwbaker** [comment]
Parked until after the sprint: others things became great priorities here. If you want it, take it!
