### ISSUE TITLE
Improve lesson objectives

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-data-intro-DEPRECATED#28]
Improve the lesson/learning objectives in the Overview box at the top of each episode e.g. https://data-lessons.github.io/library-data-intro/01-introduction/, https://data-lessons.github.io/library-data-intro/02-jargon-busting/.

Please see **Writing Learning Objectives** http://swcarpentry.github.io/instructor-training/19-lessons/.

**Comment by jcoliver** [comment]
@ccronje Has this been resolved in the current (non-deprecated) lessons?
