### ISSUE TITLE
Feedback, tips, lessons learned

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-data-intro-DEPRECATED#31]
Seeking feedback from those who have taught this lesson - please share your thoughts e.g. what worked, what didn't work, what could be improved.

Some of this feedback will be included in the lesson's [Instructor Notes](http://data-lessons.github.io/library-data-intro/guide/) as tips, or new issues to improve the lesson.

**Comment by weaverbel** [comment]
Jargon busting works really well - the people at the MIT workshop seemed to really like this, though we did get some feedback that the groups should have been smaller. I think 3-4 people per group is ideal. Any bigger and some people in a group might not get a chance to contribute. Also when defining terms, we sought feedback from the groups first before going on to give definitions - the more interactive this can be, the better. 

The file structure stuff works best in my opinion if we also try to sell people on using markdown to create the machine readable text of the future. Using proper naming conventions AND creating files that can be searched and read by machines is a good tie-in point.

**Comment by drjwbaker** [comment]
On jargon busting, during the sprint I adapted this http://data-lessons.github.io/library-data-intro/02-jargon-busting/ based on a revised version I taught it Pittsburgh.
